name: Bash script

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        labs: [ "lab1", "lab2", "lab3", "lab4" ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure
      run: |
        cd ${{ matrix.labs }}/src
        chmod +x ./test.sh
        ls
      
    - name: Build and Run
      run: ./test.sh
      shell: bash
