name: Bash script

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        labs: [ "lab1", "lab2", "lab3", "lab4" ]

    steps:
    - uses: actions/checkout@v3
    - name: Build and Launch
      run: sh ${{ matrix.labs }}/src/test.sh
