name: Makefile CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test_lab_1:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        MPI_proc: [1, 2, 4, 8, 16]
        version: [1, 2]
        
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Run
      run: |
        cd lab1/src
        make version=${{ matrix.version }} np=${{ matrix.MPI_proc }}
      
  test_lab_2:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Run
      run: | 
        cd lab2/src
        echo "Testing version 1 for 1 thread:"
        make version=1 np=1
        echo "Testing version 1 for 16 threads:"
        make version=1 np=16
        echo "Testing version 2 for 1 thread:"
        make version=2 np=1
        echo "Testing version 2 for 16 threads:"
        make version=2 np=16
        echo "Testing version 3 for 16 threads with default static schedule:"
        make version=2 np=16 schedule=static
        echo "Testing version 3 for 16 threads with custom static schedule:"
        make version=2 np=16 schedule=static,200
        echo "Testing version 3 for 16 threads with default dynamic schedule:"
        make version=2 np=16 schedule=dynamic
        echo "Testing version 3 for 16 threads with custom dynamic schedule:"
        make version=2 np=16 schedule=dynamic,200
        echo "Testing version 3 for 16 threads with default guided schedule:"
        make version=2 np=16 schedule=guided
        echo "Testing version 3 for 16 threads with custom guided schedule:"
        make version=2 np=16 schedule=guided,200
      
  test_lab_3:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Run
      run: |
        cd lab3/src
        echo "Testing for 1 process:"
        make np=1
        echo "Testing for 16 processes:"
        make np=16
      
  test_lab_4:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Run
      run: |
        cd lab4/src
        echo "Testing for 1 process:"
        make np=1
        echo "Testing for 16 processes:"
        make np=16
