name: Test Lab 1

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MPI_NP: [1, 2, 4, 8, 16]
        VERSION: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Build
        working-directory: lab1/src
        run: make build version=${{ matrix.VERSION }}
      - name: Run
        working-directory: lab1/src
        run: make run version=${{ matrix.VERSION }} np=${{ matrix.MPI_NP }}
      - name: Clean
        working-directory: lab1/src
        run: make clean version=${{ matrix.VERSION }}
