name: Test Lab 4

on:
  workflow_dispatch:
  push:
    paths:
      - "lab4"

jobs:
  test_lab_4:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MPI_NP: [1, 2, 4, 8, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Build
        working-directory: lab4/src
        run: make build
      - name: Run
        working-directory: lab4/src
        run: make run np=${{ matrix.MPI_NP }}
      - name: Clean
        working-directory: lab4/src
        run: make clean
